# Generated by Django 4.0.3 on 2022-04-13 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feriadomodel_modificado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriadomodel',
            name='modificado_em',
        ),
    ]
